name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        # Full git history is needed to get a proper list of changed files
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        
    - name: Run Black
      run: black .
        
    - name: Commit changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Apply automatic formatting changes"
          git push
        else
          echo "No changes to commit"
        fi 